// <auto-generated />
using System;
using MasterDetails.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterDetails.API.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250705124911_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterDetails.API.Entities.Blog", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BlogID");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogID = 1,
                            Author = "John Doe",
                            Content = "This blog post covers the new features in C# 10...",
                            CoverImageUrl = "https://example.com/images/csharp10.png",
                            CreatedAt = new DateTime(2025, 7, 5, 18, 49, 10, 901, DateTimeKind.Local).AddTicks(156),
                            IsPublished = true,
                            Tags = "C#, .NET, Programming",
                            Title = "Introduction to C# 10"
                        },
                        new
                        {
                            BlogID = 2,
                            Author = "Jane Smith",
                            Content = "Learn how to build web applications using ASP.NET Core...",
                            CoverImageUrl = "https://example.com/images/aspnetcore.png",
                            CreatedAt = new DateTime(2025, 7, 5, 18, 49, 10, 901, DateTimeKind.Local).AddTicks(171),
                            IsPublished = true,
                            Tags = "ASP.NET Core, Web Development",
                            Title = "Getting Started with ASP.NET Core"
                        });
                });

            modelBuilder.Entity("MasterDetails.API.Entities.BlogVideo", b =>
                {
                    b.Property<int>("BlogVideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogVideoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogVideoID"));

                    b.Property<int>("BlogID")
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BlogVideoID");

                    b.HasIndex("BlogID");

                    b.ToTable("BlogVideos");

                    b.HasData(
                        new
                        {
                            BlogVideoID = 1,
                            BlogID = 1,
                            Caption = "C# 10 New Features Overview",
                            DisplayOrder = 1,
                            VideoUrl = "https://www.youtube.com/embed/dQw4w9WgXcQ"
                        },
                        new
                        {
                            BlogVideoID = 2,
                            BlogID = 1,
                            Caption = "Advanced C# 10 Tips",
                            DisplayOrder = 2,
                            VideoUrl = "https://www.youtube.com/embed/oHg5SJYRHA0"
                        },
                        new
                        {
                            BlogVideoID = 3,
                            BlogID = 2,
                            Caption = "ASP.NET Core Beginner Tutorial",
                            DisplayOrder = 1,
                            VideoUrl = "https://www.youtube.com/embed/abcdefg1234"
                        });
                });

            modelBuilder.Entity("MasterDetails.API.Entities.BlogVideo", b =>
                {
                    b.HasOne("MasterDetails.API.Entities.Blog", "Blog")
                        .WithMany("BlogVideos")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("MasterDetails.API.Entities.Blog", b =>
                {
                    b.Navigation("BlogVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
